# Cross Validation

In [41]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import LeaveOneOut, cross_val_score, train_test_split, KFold, StratifiedKFold
from sklearn.linear_model import LinearRegression, LogisticRegression

In [32]:
df = pd.read_csv('../../datasets/BostonHousing.csv')
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2


In [33]:
df.shape

(506, 14)

In [34]:
x = df.iloc[:,:13]
y = df.iloc[:,-1]

### Hold out approach

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [36]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
print(r2_score(y_test, y_pred), mean_squared_error(y_test, y_pred), sep='\n')

0.668759493535632
24.291119474973517


### Leave One Out CV

In [37]:
loo = LeaveOneOut()
lr = LinearRegression()

scale = StandardScaler()
x_scale = scale.fit_transform(x)

scores = cross_val_score(lr, x_scale, y, cv=loo, scoring='neg_mean_squared_error', n_jobs=-1)

mse_score = abs(scores)
mse_score.mean()

np.float64(23.72574551947614)

### K Fold

In [38]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)
lr = LinearRegression()

scale = StandardScaler()
x_scale = scale.fit_transform(x)

r2_scores = cross_val_score(lr, x, y, cv=kfold, scoring='r2', n_jobs=-1)
mse_scores = cross_val_score(lr, x, y, cv=kfold, scoring='neg_mean_squared_error', n_jobs=-1)

print(r2_scores, r2_scores.mean())
print(abs(mse_scores),abs(mse_scores.mean()))

[0.66875949 0.7342547  0.70986601 0.77595168 0.68727731] 0.7152218388256883
[24.29111947 20.86790094 26.39596869 23.40122508 22.48676421] 23.488595677968643


### Stratified K Fold

In [39]:
skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=149)
lr_class = LogisticRegression()

y = df.pop('rad')
x = df

scale = StandardScaler()
x_scale = scale.fit_transform(x)

accuracy_score = cross_val_score(lr_class, x, y, cv=skfold, scoring='accuracy', n_jobs=-1)

print(accuracy_score, accuracy_score.mean())

[0.59803922 0.53465347 0.55445545 0.65346535 0.59405941] 0.5869345758105223
