# Incremental PCA

In [37]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import IncrementalPCA, PCA

In [31]:
x = np.random.random(size=(10000, 50))
x.shape

(10000, 50)

In [32]:
# mean centric
scale = StandardScaler()
x = scale.fit_transform(x)

In [33]:
# implementing pca
ipca = IncrementalPCA(n_components=5, batch_size=1000)
x_transform = ipca.fit_transform(x)

In [34]:
x_transform.shape

(10000, 5)

In [35]:
ipca.components_

array([[ 0.08152049,  0.00285145, -0.10028631, -0.0200253 ,  0.34809692,
         0.02538999,  0.10864953,  0.10330979,  0.22287653, -0.01650329,
        -0.17875882,  0.09245012, -0.21851138,  0.10201842,  0.28534438,
         0.08833725,  0.09374023, -0.2257049 ,  0.16724443,  0.00731207,
         0.02345189, -0.20438753, -0.07171434, -0.05007251,  0.01901624,
         0.02515636, -0.10107429,  0.2495724 ,  0.10798816, -0.16162115,
        -0.08092752, -0.1519693 ,  0.04686356,  0.04310982, -0.01953041,
        -0.13417298,  0.19643827, -0.03945593,  0.21010465, -0.28180535,
        -0.17946594, -0.05967397, -0.03889485,  0.00721982, -0.06907575,
         0.24156469, -0.0739694 ,  0.05070958,  0.13950017,  0.08950135],
       [ 0.18851236, -0.19323044,  0.20137153, -0.16659243, -0.18072574,
         0.11743501,  0.03073962,  0.00084147, -0.0886772 ,  0.35982329,
         0.00677337,  0.01075175, -0.02734366,  0.05598586,  0.05230569,
        -0.14361505, -0.1345601 , -0.16820695,  0.

In [36]:
ipca.explained_variance_

array([1.10315683, 1.06816036, 1.04928414, 1.03817527, 0.99971193])

## PCA

In [38]:
pca = PCA(n_components=5)
x_transform = pca.fit_transform(x)

x_transform.shape

(10000, 5)

In [39]:
pca.explained_variance_

array([1.15288854, 1.15116009, 1.12618032, 1.12316828, 1.10705592])