# Principle Component Analysis

In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [7]:
np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df, df1],ignore_index=True)

df = df.sample(40)

In [8]:
df.head()

,feature1,feature2,feature3,target
2,-0.367548,-1.137460,-1.322148,1
34,0.177061,-0.598109,1.226512,0
14,0.420623,0.411620,-0.071324,1
11,1.968435,-0.547788,-0.679418,1
12,-2.506230,0.146960,0.606195,1


In [15]:
# Apply StandardScaler
scale = StandardScaler()
df.iloc[:,0:3] = scale.fit_transform(df.iloc[:,0:3])
df.head()

,feature1,feature2,feature3,target
2,-0.700809,-1.525586,-1.749156,1
34,-0.224481,-1.010757,0.491251,0
14,-0.011456,-0.046935,-0.649616,1
11,1.342296,-0.962723,-1.184163,1
12,-2.571350,-0.299561,-0.054040,1


In [18]:
# Covariance Matrix
cov_matrix = np.cov(df.iloc[:,0:3].T)
cov_matrix

array([[1.02564103, 0.20478114, 0.080118  ],
       [0.20478114, 1.02564103, 0.19838882],
       [0.080118  , 0.19838882, 1.02564103]])

In [19]:
# Eigen Values - Eignen Vectors
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)
print(eigen_values, eigen_vectors, sep='\n')

[1.3536065  0.94557084 0.77774573]
[[-0.53875915 -0.69363291  0.47813384]
 [-0.65608325 -0.01057596 -0.75461442]
 [-0.52848211  0.72025103  0.44938304]]


### 3D to 1D

In [54]:
pc1 = eigen_vectors[:,:1]
pc1.shape

(3, 1)

In [55]:
one_dim_transform = np.dot(df.iloc[:,:3], pc1)
df_1D = pd.DataFrame(one_dim_transform, columns=['PCA1'])
df_1D['target'] = df[['target']]

In [56]:
df_1D.head()

,PCA1,target
0,2.302877,1
1,0.524464,1
2,0.380275,1
3,0.534262,1
4,1.610434,1


### 3D to 2D

In [58]:
pca2 = eigen_vectors[:,0:2]
pca2.shape

(3, 2)

In [59]:
two_dim_transform = np.dot(df.iloc[:,0:3], pca2)
df_2D = pd.DataFrame(two_dim_transform, columns=['PCA1', 'PCA2'])
df_2D['target'] = df['target']
df_2D.head()

,PCA1,PCA2,target
0,2.302877,-0.757593,1
1,0.524464,0.520221,1
2,0.380275,-0.459443,1
3,0.534262,-1.773773,1
4,1.610434,1.747819,1


## Using SKlearn

In [60]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_pca = pca.fit_transform(df.iloc[:,0:3])
new_df_2D = pd.DataFrame(x_pca, columns=['PCA1', 'PCA2'])

In [61]:
new_df_2D['target'] = df['target']
new_df_2D.head()

,PCA1,PCA2,target
0,-2.302877,-0.757593,1
1,-0.524464,0.520221,1
2,-0.380275,-0.459443,1
3,-0.534262,-1.773773,1
4,-1.610434,1.747819,1


In [62]:
pca.explained_variance_ # returns eigen values

array([1.3536065 , 0.94557084])

In [64]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [65]:
pca.components_ # returns eigen vectors

array([[ 0.53875915,  0.65608325,  0.52848211],
       [-0.69363291, -0.01057596,  0.72025103]])

In [66]:
pca2

array([[-0.53875915, -0.69363291],
       [-0.65608325, -0.01057596],
       [-0.52848211,  0.72025103]])